security:
    #Выбор алгоритма шифрования
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        user:
            entity:
                class: App\Entity\User
                property: email
    #Параметры защиты
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: user
            logout:
                path:   /logout
                target: /
            guard:
                authenticator:
                   - app.security.login_form_authenticator
    #Иерархия ролей пользователей
    role_hierarchy:
        ROLE_ADMIN: [ROLE_OPERATOR, ROLE_MANAGER]
    #Разграничение прав доступа
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/users, roles: ROLE_ADMIN }
        - { path: ^/admin/applications, roles: [ROLE_MANAGER] }
        - { path: ^/admin/clients, roles: [ROLE_MANAGER] }
        - { path: ^/admin, roles: [ROLE_ADMIN] }
        - { path: ^/consult, roles: [ROLE_OPERATOR] }


