language: php

sudo: false

deploy:
  provider: heroku
  api_key:
    secure: "fe725629-7db6-484d-bcae-13bf55cb537c"
  on: production

before_install:
  - composer self-update

install:
  - composer install
  - composer update